### ISSUE TITLE
IDEA15 mybatis插件替换后无效

### ISSUE THREAD

**Issue by ojeo** [myoss/profile#1]
IntelliJ IDEA 15.0
Build #IU-143.381, built on October 30, 2015
JRE: 1.8.0_05-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

插件版本<version>2.51</version>

替换这几个 class文件后，不提示注册了，但是插件没有效果，在dao上也不显示跳转到 mapper文件的图标了

**Comment by myoss** [comment]
已经修复了，新添加了3个calss文件，多谢你的发现。

参考提交：https://github.com/myoss/profile/commit/59eeeb3cde27010b406f16e0c2caac94fe87010c

**Comment by ojeo** [comment]
试过可以了 谢谢
