### ISSUE TITLE
2016.3版本失败

### ISSUE THREAD

**Issue by Da-Hong** [myoss/profile#14]
还是提示需要activecode

**Comment by Da-Hong** [comment]
该替换的都替换了

**Comment by myoss** [comment]
没报错呀，我也升级到了`2016.3`，`mybatis plugin`的版本还是`2.87`

**Comment by beamaster** [comment]
@Da-Hong  这位同学，可以参考我整理的资料看看，有问题交流[mac 破解mybatis插件](https://beamaster.github.io/2017/01/03/IDEA-for-Mybatis-破解之道/)

**Comment by myoss** [comment]
参考[wiki](https://github.com/myoss/profile/wiki/Mybatis-Plugin%E6%8F%92%E4%BB%B6%E5%AD%A6%E4%B9%A0%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)替换方法
