### ISSUE TITLE
Mybatis Plugin 2.53的破解

### ISSUE THREAD

**Issue by xinshitn** [myoss/profile#2]
测试这个版本能够正常破解，功能可用，但是每次打开会有注册码验证失败的提示框，虽然不影响使用，但是每次出这个提示框很不舒服，能看看是什么原因尝试解决下吗

**Comment by myoss** [comment]
最近工作忙，还没来得及更新2.53版本，我尽快抽时间看下，先委屈用几天吧，争取周末解决

**Comment by myoss** [comment]
我中午更新了mybatis插件，用v2.51中的class替换，重启idea后没有你说的这个问题。你是不是少替换文件了，或者目录不对？要不你先删掉插件，然后重新下载，用WinRar打开mybatis_plus.jar，然后将com文件夹直接拖拽进去替换，不用每个文件去替换。我晚上回去试试家里电脑看看，其他兄弟有同样的问题，还请在这里回复一下

**Comment by xinshitn** [comment]
嗯，我再试试。对了，忘了说环境，我是MAC版的idea15

**Comment by wtjperi2003** [comment]
我试试看

**Comment by wtjperi2003** [comment]
没问题，启动没有什么提示。我是win7 64位 idea15

**Comment by xinshitn** [comment]
难道是MAC版有差异？我MAC系统是10.11.1，应该是完全覆盖jar包下的com就可以了吧？还有别的要覆盖吗

**Comment by myoss** [comment]
@xinshitn 你把你替换后的jar上传到这里或者百度云地址，我下载下来试试看，我没有mac环境。

**Comment by xinshitn** [comment]
好的，上传在百度云了
http://pan.baidu.com/s/1c07HdIg

**Comment by myoss** [comment]
@xinshitn 我更新了使用手册，你按mac os里的方法找到这个文件，再替换。我用你给我的jar包，在mac os里使用没有要注册的提示，正常使用，希望这次能给你解决困扰。

https://github.com/myoss/profile/blob/master/idea/plugin/MybatisPlugin/%E7%A0%B4%E8%A7%A3Mybatis-Plugin%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95.txt

**Comment by xinshitn** [comment]
嗯，我mac下直接替换还是不行，我台式机上Win10是成功了的，晚上回去把win10的jar包直接覆盖到mac的目录下试试看。
另外：在mac下查找那个目录，如果不想用终端命令的话，还有个办法，下载个例如AppCleaner的免费卸载软件，把idea拖入会搜索出所有的相关目录，找到IntelliJIdea15的目录打开就行（千万别点删除，那就卸载了...）

**Comment by myoss** [comment]
你这个有点诡异了呀，加我QQ吧1005050799，搞不懂了。
