### ISSUE TITLE
2.6可以使用这个破解吗

### ISSUE THREAD

**Issue by galaxist** [myoss/profile#3]
mybatis新的2.6版插件可以用这个方式破解吗？

**Comment by JasonMing** [comment]
2.6的更新提示就是更新激活机制，感觉需要等一段时间。。。先用着2.53先吧。。。

**Comment by jianyking** [comment]
2.6的破解出来了吗

**Comment by myoss** [comment]
我用的IntelliJ Idea的版本是15.0.3，Idea不推送2.6的版本，你们用的什么版本？我看了下插件它的更新日志，没有新功能，用不着可以追求新版本

**Comment by ylxs90** [comment]
2.6的已经不能用了，刚刚在mac上装了。 可是我现在都找不到2.5的版本。这下给跪了

**Comment by myoss** [comment]
2.64版本已经更新了。[https://github.com/myoss/profile/tree/master/idea/plugin/MybatisPlugin/v2.64](https://github.com/myoss/profile/tree/master/idea/plugin/MybatisPlugin/v2.64)
