### ISSUE TITLE
2.65 替换了com文件夹没有效果

### ISSUE THREAD

**Issue by kingwrcy** [myoss/profile#5]
windows 7,idea 15.0.4
mybatis plugin 2.65

**Comment by myoss** [comment]
麻烦提供你替换后的jar文件

**Comment by kingwrcy** [comment]
@myoss 传到了百度云
http://pan.baidu.com/s/1i3NaHDF

昨天替换启动没变化,今天又试了一次,启动报错,无法启动,换回自带的jar才行
