### ISSUE TITLE
mac上2016.1使用后程序崩溃

### ISSUE THREAD

**Issue by colin-lee** [myoss/profile#6]
启动之后，一旦点击mapper相关的类，idea就崩溃了

**Comment by myoss** [comment]
上传下你替换后的jar包来看看吧

**Comment by colin-lee** [comment]
[mybatis_plus.zip](https://github.com/myoss/profile/files/187447/mybatis_plus.zip)
请查收

**Comment by myoss** [comment]
给百度云的地址吧，下载不了

**Comment by colin-lee** [comment]
链接: http://pan.baidu.com/s/1jInN1wM 密码: qgb4

**Comment by myoss** [comment]
我测试过你给我jar包，在windows和mac系统下都没有问题，可以使用

![qq 20160325134937](https://cloud.githubusercontent.com/assets/6986459/14039129/f1a4c9e6-f293-11e5-830a-1751dc785364.png)

**Comment by piggsoft** [comment]
windows下替换后，也存在崩溃的现象

**Comment by myoss** [comment]
如果只是偶尔的崩溃，我也没法解决，这是插件本身的问题，如果使用了之后，无法打开，请先确认是不是替换操作有问题，如果还是不行，提供下jar包。 @piggsoft

**Comment by piggsoft** [comment]
对了，你这个jar是需要项目的jdk版本是1.8？

**Comment by piggsoft** [comment]
我们有qq群可以讨论吗？

**Comment by myoss** [comment]
2.7版本用jdk1.8编译的，没有qq群讨论，IntelliJ Idea 2015能获取2.7版本的更新？

| Version |	Compatible builds | Date |
| ------- | ----------------- | ---- |
| 2.7 | 145.257 — 145.* | 18.03.2016 |
| 2.65 | 143.379 — 143.* | 29.02.2016 |
| 2.492 | 141.177 — 141.* | 14.01.2016 |

**Comment by piggsoft** [comment]
恩，我装了16 plugin的版本是2.7
现在我退回15，plugin的版本2.65
也会出现这个问题
去掉plugin就正常了

**Comment by myoss** [comment]
感觉是你替换有问题，2.65发布有一段时间了，没有人反映有问题。我没有测试过你替换后的jar，我不知道你这是什么问题

**Comment by piggsoft** [comment]
我怎么将包发给你？

**Comment by piggsoft** [comment]
http://pan.baidu.com/s/1o7Z2ZUy

**Comment by myoss** [comment]
我试了你的没有问题呀
![qq 20160331101358](https://cloud.githubusercontent.com/assets/6986459/14163651/1a37b8ce-f72a-11e5-859f-889fded07b73.png)
![qq 20160331102036](https://cloud.githubusercontent.com/assets/6986459/14163675/3c9ca6fe-f72a-11e5-8d85-e3c17cabc4ba.png)

**Comment by piggsoft** [comment]
你这样操作下，你关闭IDEA，关闭之前不打开任何文件，再打开，然后打开dao。就崩溃了

**Comment by piggsoft** [comment]
版本和你一样

**Comment by piggsoft** [comment]
有源码吗？可以的话给分源码 我来瞅瞅？

**Comment by myoss** [comment]
我没有测试出来，你直接反编译我上传的class好了，我都是用idea反编译的

**Comment by myoss** [comment]
http://pan.baidu.com/s/1jHX9sY6  @piggsoft 我应该找到原因了，你用这个重新替换（Idea 2016.1 jdk1.8），告诉我结果

**Comment by piggsoft** [comment]
好像是没问题了，是什么原因导致的？
我再试试,issue 先别关

**Comment by myoss** [comment]
插件新版本加了代码进行强制退出。。。。难怪我的idea老是弹出退出的提示，只是因为我的idea设置退出需要确认，估计你们的是直接退出

时不时弹出这个
![qq 20160331125916](https://cloud.githubusercontent.com/assets/6986459/14166951/565104a8-f74a-11e5-94b5-11812630eb15.png)

我的idea设置
![qq 20160331130003](https://cloud.githubusercontent.com/assets/6986459/14166958/5fe186fa-f74a-11e5-8deb-d2fe36bde948.png)

**Comment by piggsoft** [comment]
代码的源码给我一份，我们一起开发？

发自我的 iPhone

**Comment by kingwrcy** [comment]
@myoss 插件新版本加了代码进行强制退出

这是什么意思,为什么要强行退出?

我的idea 2016 用了替换后的jar后各种自动退出,我直接删了插件再启动idea就没问题,已经解决吗还是没解决?

**Comment by myoss** [comment]
这是插件加的代码好不好。。。。。[https://github.com/myoss/profile/tree/master/idea/plugin/MybatisPlugin/v2.7_update](https://github.com/myoss/profile/tree/master/idea/plugin/MybatisPlugin/v2.7_update)
