### ISSUE TITLE
mac下配置

### ISSUE THREAD

**Issue by Jiar** [myoss/profile#8]
mac下配置和windows下配置操作基本一样，不过路径不同
mac下路径为：/Users/用户名/Library/Application Support/IntelliJIdea2016.1/mybatis_plus/lib
用下作者的博文：http://myoss.github.io/2016/MyBatis-Plugin-%E5%AD%A6%E4%B9%A0%E4%BD%BF%E7%94%A8/
在以上博文说明基础上：把mac路径下的mybatis_plus.jar拷贝到windows下，使用winrar执行替换jar内部.class文件操作，最后将提换好后的mybatis_plus.jar拷贝回mac系统路径下替换原jar文件即可。

**Comment by paralleld** [comment]
https://docs.oracle.com/javase/tutorial/deployment/jar/update.html

可以在mac命令行下面直接更新jar文件。

**Comment by Teddy-Zhu** [comment]
intellij idea 2016.2 mac 貌似失效了

**Comment by GitHanter** [comment]
com.seventh7.mybatis.setting.MybatisSetting cannot be cast to com.seventh7.mybatis.setting.MybatisSetting 这个错误怎么解决呢，Inellij IDEA 2016.1.4 Windows,  mybatis_plus 2.85.

**Comment by myoss** [comment]
@GitHanter 这个错误你提issue给这个插件的开发者吧，是它本身的问题，我无力解决。或者你用mybatis官方的插件是生成

**Comment by GitHanter** [comment]
@myoss 谢了，官网花了200块买了个License，直接下载原文件安装，还是报同样的错，得和开发者撕了

**Comment by Adol1111** [comment]
@myoss mac上 intellij idea 2016.2 无效，版本2.86

替换以后还是显示 Mybatis Plugin is not activated yet

**Comment by zzvv** [comment]
idea 2016 02，Mac 10.11.6，替换成功。无提示

**Comment by beamaster** [comment]
系统环境：`macOS sierra 10.12.2`
idea环境：`idea 2016 03 ` 
替换成功，正常使用

**Comment by myoss** [comment]
@Adol1111 参考[wiki](https://github.com/myoss/profile/wiki/Mybatis-Plugin%E6%8F%92%E4%BB%B6%E5%AD%A6%E4%B9%A0%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)替换方法
